-- ============================================================
-- Padel Pro - MySQL Seed Script
-- Source: backend/padel_pro.db
-- ============================================================

SET FOREIGN_KEY_CHECKS = 0;

-- ------------------------------------------------------------
-- Table: audit_logs
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `audit_logs`;
CREATE TABLE IF NOT EXISTS `audit_logs` (`id` TEXT NULL  PRIMARY KEY, `admin_name` TEXT NOT NULL , `admin_email` TEXT NOT NULL , `action` TEXT NOT NULL , `target` TEXT NOT NULL , `details` TEXT NULL , `timestamp` TEXT NOT NULL );

INSERT INTO `audit_logs` (`id`, `admin_name`, `admin_email`, `action`, `target`, `details`, `timestamp`) VALUES ('audit_01', 'Carlos Gómez', 'carlos@padelpro.app', 'MODIFICACION_PARTIDO', 'Partido #match_live_01', 'Pista actualizada de Pista 2 a Pista Central por retransmisión televisiva', '2026-08-08 11:15:00') ON DUPLICATE KEY UPDATE id = VALUES(id), admin_name = VALUES(admin_name), admin_email = VALUES(admin_email), action = VALUES(action), target = VALUES(target), details = VALUES(details), timestamp = VALUES(timestamp);
INSERT INTO `audit_logs` (`id`, `admin_name`, `admin_email`, `action`, `target`, `details`, `timestamp`) VALUES ('audit_02', 'Carlos Gómez', 'carlos@padelpro.app', 'APROBACION_INSCRIPCION', 'Pareja Coello/Tapia', 'Inscripción confirmada para Premier Padel Major Madrid', '2026-08-08 10:00:00') ON DUPLICATE KEY UPDATE id = VALUES(id), admin_name = VALUES(admin_name), admin_email = VALUES(admin_email), action = VALUES(action), target = VALUES(target), details = VALUES(details), timestamp = VALUES(timestamp);
INSERT INTO `audit_logs` (`id`, `admin_name`, `admin_email`, `action`, `target`, `details`, `timestamp`) VALUES ('audit_03', 'Sistema Automático', 'system@padelpro.app', 'REGLAS_TORNEO', 'Copa Abierta Barcelona', 'Modo Punto de Oro activado para todos los partidos de fase de grupos', '2026-08-07 18:30:00') ON DUPLICATE KEY UPDATE id = VALUES(id), admin_name = VALUES(admin_name), admin_email = VALUES(admin_email), action = VALUES(action), target = VALUES(target), details = VALUES(details), timestamp = VALUES(timestamp);

-- ------------------------------------------------------------
-- Table: courts
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `courts`;
CREATE TABLE IF NOT EXISTS `courts` (`id` TEXT NULL  PRIMARY KEY, `name` TEXT NOT NULL , `location` TEXT NOT NULL , `number` INTEGER NOT NULL , `status` TEXT NOT NULL , `current_match_id` TEXT NULL );

INSERT INTO `courts` (`id`, `name`, `location`, `number`, `status`, `current_match_id`) VALUES ('crt_central', 'Pista Central (Estadio)', 'Club Central', '1', 'OCCUPIED', 'match_live_01') ON DUPLICATE KEY UPDATE id = VALUES(id), name = VALUES(name), location = VALUES(location), number = VALUES(number), status = VALUES(status), current_match_id = VALUES(current_match_id);
INSERT INTO `courts` (`id`, `name`, `location`, `number`, `status`, `current_match_id`) VALUES ('crt_2', 'Pista 2 Panorámica', 'Club Central', '2', 'AVAILABLE', NULL) ON DUPLICATE KEY UPDATE id = VALUES(id), name = VALUES(name), location = VALUES(location), number = VALUES(number), status = VALUES(status), current_match_id = VALUES(current_match_id);
INSERT INTO `courts` (`id`, `name`, `location`, `number`, `status`, `current_match_id`) VALUES ('crt_3', 'Pista 3 Cristal Norte', 'Anexo Norte', '3', 'AVAILABLE', NULL) ON DUPLICATE KEY UPDATE id = VALUES(id), name = VALUES(name), location = VALUES(location), number = VALUES(number), status = VALUES(status), current_match_id = VALUES(current_match_id);
INSERT INTO `courts` (`id`, `name`, `location`, `number`, `status`, `current_match_id`) VALUES ('crt_4', 'Pista 4 Cubierta', 'Anexo Sur', '4', 'AVAILABLE', NULL) ON DUPLICATE KEY UPDATE id = VALUES(id), name = VALUES(name), location = VALUES(location), number = VALUES(number), status = VALUES(status), current_match_id = VALUES(current_match_id);

-- ------------------------------------------------------------
-- Table: gesture_config
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `gesture_config`;
CREATE TABLE IF NOT EXISTS `gesture_config` (`id` INTEGER NULL  PRIMARY KEY, `point_team_a_gesture` TEXT NOT NULL , `point_team_b_gesture` TEXT NOT NULL , `undo_gesture` TEXT NOT NULL , `pause_timer_gesture` TEXT NOT NULL , `resume_timer_gesture` TEXT NOT NULL , `cooldown_ms` INTEGER NOT NULL , `min_confidence` REAL NOT NULL , `required_hold_frames` INTEGER NOT NULL , `detection_zone` TEXT NULL , `mode` TEXT NOT NULL );

INSERT INTO `gesture_config` (`id`, `point_team_a_gesture`, `point_team_b_gesture`, `undo_gesture`, `pause_timer_gesture`, `resume_timer_gesture`, `cooldown_ms`, `min_confidence`, `required_hold_frames`, `detection_zone`, `mode`) VALUES ('1', 'OPEN_PALM', 'FIST', 'THUMB_DOWN', 'HORIZONTAL_PALM', 'THUMB_UP', '500', '0.8', '15', '{"enabled": true, "x_min": 0, "y_min": 0, "x_max": 640, "y_max": 480}', 'ONE_HAND') ON DUPLICATE KEY UPDATE id = VALUES(id), point_team_a_gesture = VALUES(point_team_a_gesture), point_team_b_gesture = VALUES(point_team_b_gesture), undo_gesture = VALUES(undo_gesture), pause_timer_gesture = VALUES(pause_timer_gesture), resume_timer_gesture = VALUES(resume_timer_gesture), cooldown_ms = VALUES(cooldown_ms), min_confidence = VALUES(min_confidence), required_hold_frames = VALUES(required_hold_frames), detection_zone = VALUES(detection_zone), mode = VALUES(mode);

-- ------------------------------------------------------------
-- Table: match_events
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `match_events`;
CREATE TABLE IF NOT EXISTS `match_events` (`id` TEXT NULL  PRIMARY KEY, `match_id` TEXT NOT NULL , `set_number` INTEGER NOT NULL , `game_number` INTEGER NOT NULL , `timestamp` TEXT NOT NULL , `winning_pair_id` TEXT NOT NULL , `player_id` TEXT NULL , `player_name` TEXT NULL , `event_type` TEXT NOT NULL , `description` TEXT NULL , `score_snapshot` TEXT NULL );


-- ------------------------------------------------------------
-- Table: matches
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `matches`;
CREATE TABLE IF NOT EXISTS `matches` (`id` TEXT NULL  PRIMARY KEY, `tournament_id` TEXT NULL , `tournament_name` TEXT NULL , `court_id` TEXT NULL , `court_name` TEXT NOT NULL , `date_time` TEXT NOT NULL , `pair_a_id` TEXT NOT NULL , `pair_b_id` TEXT NOT NULL , `pair_a_name` TEXT NOT NULL , `pair_b_name` TEXT NOT NULL , `player_a1_id` TEXT NOT NULL , `player_a2_id` TEXT NOT NULL , `player_b1_id` TEXT NOT NULL , `player_b2_id` TEXT NOT NULL , `player_a1_name` TEXT NOT NULL , `player_a2_name` TEXT NOT NULL , `player_b1_name` TEXT NOT NULL , `player_b2_name` TEXT NOT NULL , `player_a1_avatar` TEXT NULL , `player_a2_avatar` TEXT NULL , `player_b1_avatar` TEXT NULL , `player_b2_avatar` TEXT NULL , `status` TEXT NOT NULL , `sets` TEXT NULL , `current_game` TEXT NULL , `current_set_index` INTEGER NULL , `winner_pair_id` TEXT NULL , `winner_team` TEXT NULL , `start_time_ms` INTEGER NULL , `elapsed_time_sec` INTEGER NOT NULL , `golden_point` INTEGER NOT NULL , `sets_to_win` INTEGER NOT NULL , `round_name` TEXT NULL );

INSERT INTO `matches` (`id`, `tournament_id`, `tournament_name`, `court_id`, `court_name`, `date_time`, `pair_a_id`, `pair_b_id`, `pair_a_name`, `pair_b_name`, `player_a1_id`, `player_a2_id`, `player_b1_id`, `player_b2_id`, `player_a1_name`, `player_a2_name`, `player_b1_name`, `player_b2_name`, `player_a1_avatar`, `player_a2_avatar`, `player_b1_avatar`, `player_b2_avatar`, `status`, `sets`, `current_game`, `current_set_index`, `winner_pair_id`, `winner_team`, `start_time_ms`, `elapsed_time_sec`, `golden_point`, `sets_to_win`, `round_name`) VALUES ('match_live_01', 'tour_major_madrid', 'Premier Padel Major Madrid 2026', 'crt_central', 'Pista Central (Estadio)', '2026-08-08 11:30', 'pair_galan_lebron', 'pair_coello_tapia', 'Galán / Lebrón', 'Coello / Tapia', 'usr_ale_galan', 'usr_juan_lebron', 'usr_arturo_coello', 'usr_agustin_tapia', 'Alejandro Galán', 'Juan Lebrón', 'Arturo Coello', 'Agustín Tapia', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80', 'LIVE', '[{"team_a_games": 6, "team_b_games": 4, "is_tie_break": false, "winner": "A"}, {"team_a_games": 3, "team_b_games": 6, "is_tie_break": false, "winner": "B"}, {"team_a_games": 3, "team_b_games": 2, "is_tie_break": false}]', '{"team_a_points": "30", "team_b_points": "15", "server_team": "A", "is_deuce": false}', '2', NULL, NULL, NULL, '5240', '1', '2', 'Gran Final') ON DUPLICATE KEY UPDATE id = VALUES(id), tournament_id = VALUES(tournament_id), tournament_name = VALUES(tournament_name), court_id = VALUES(court_id), court_name = VALUES(court_name), date_time = VALUES(date_time), pair_a_id = VALUES(pair_a_id), pair_b_id = VALUES(pair_b_id), pair_a_name = VALUES(pair_a_name), pair_b_name = VALUES(pair_b_name), player_a1_id = VALUES(player_a1_id), player_a2_id = VALUES(player_a2_id), player_b1_id = VALUES(player_b1_id), player_b2_id = VALUES(player_b2_id), player_a1_name = VALUES(player_a1_name), player_a2_name = VALUES(player_a2_name), player_b1_name = VALUES(player_b1_name), player_b2_name = VALUES(player_b2_name), player_a1_avatar = VALUES(player_a1_avatar), player_a2_avatar = VALUES(player_a2_avatar), player_b1_avatar = VALUES(player_b1_avatar), player_b2_avatar = VALUES(player_b2_avatar), status = VALUES(status), sets = VALUES(sets), current_game = VALUES(current_game), current_set_index = VALUES(current_set_index), winner_pair_id = VALUES(winner_pair_id), winner_team = VALUES(winner_team), start_time_ms = VALUES(start_time_ms), elapsed_time_sec = VALUES(elapsed_time_sec), golden_point = VALUES(golden_point), sets_to_win = VALUES(sets_to_win), round_name = VALUES(round_name);
INSERT INTO `matches` (`id`, `tournament_id`, `tournament_name`, `court_id`, `court_name`, `date_time`, `pair_a_id`, `pair_b_id`, `pair_a_name`, `pair_b_name`, `player_a1_id`, `player_a2_id`, `player_b1_id`, `player_b2_id`, `player_a1_name`, `player_a2_name`, `player_b1_name`, `player_b2_name`, `player_a1_avatar`, `player_a2_avatar`, `player_b1_avatar`, `player_b2_avatar`, `status`, `sets`, `current_game`, `current_set_index`, `winner_pair_id`, `winner_team`, `start_time_ms`, `elapsed_time_sec`, `golden_point`, `sets_to_win`, `round_name`) VALUES ('match_upcoming_02', 'tour_major_madrid', 'Premier Padel Major Madrid 2026', 'crt_2', 'Pista 2 Panorámica', '2026-08-08 18:30', 'pair_chingotto_navarro', 'pair_stupaczuk_dinenno', 'Chingotto / Navarro', 'Stupaczuk / Di Nenno', 'usr_chingotto', 'usr_paquito', 'usr_stupa', 'usr_dinenno', 'Fede Chingotto', 'Paquito Navarro', 'Franco Stupaczuk', 'Martin Di Nenno', 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150&auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80', 'UPCOMING', '[{"team_a_games": 0, "team_b_games": 0, "is_tie_break": false, "tie_break_points": {"team_a": 0, "team_b": 0}}]', '{"team_a_points": "0", "team_b_points": "0", "server_team": "A", "is_deuce": false}', '0', NULL, NULL, NULL, '0', '1', '2', 'Cuartos de Final') ON DUPLICATE KEY UPDATE id = VALUES(id), tournament_id = VALUES(tournament_id), tournament_name = VALUES(tournament_name), court_id = VALUES(court_id), court_name = VALUES(court_name), date_time = VALUES(date_time), pair_a_id = VALUES(pair_a_id), pair_b_id = VALUES(pair_b_id), pair_a_name = VALUES(pair_a_name), pair_b_name = VALUES(pair_b_name), player_a1_id = VALUES(player_a1_id), player_a2_id = VALUES(player_a2_id), player_b1_id = VALUES(player_b1_id), player_b2_id = VALUES(player_b2_id), player_a1_name = VALUES(player_a1_name), player_a2_name = VALUES(player_a2_name), player_b1_name = VALUES(player_b1_name), player_b2_name = VALUES(player_b2_name), player_a1_avatar = VALUES(player_a1_avatar), player_a2_avatar = VALUES(player_a2_avatar), player_b1_avatar = VALUES(player_b1_avatar), player_b2_avatar = VALUES(player_b2_avatar), status = VALUES(status), sets = VALUES(sets), current_game = VALUES(current_game), current_set_index = VALUES(current_set_index), winner_pair_id = VALUES(winner_pair_id), winner_team = VALUES(winner_team), start_time_ms = VALUES(start_time_ms), elapsed_time_sec = VALUES(elapsed_time_sec), golden_point = VALUES(golden_point), sets_to_win = VALUES(sets_to_win), round_name = VALUES(round_name);

-- ------------------------------------------------------------
-- Table: notifications
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `notifications`;
CREATE TABLE IF NOT EXISTS `notifications` (`id` TEXT NULL  PRIMARY KEY, `title` TEXT NOT NULL , `body` TEXT NULL , `timestamp` TEXT NOT NULL , `read` INTEGER NOT NULL , `type` TEXT NOT NULL , `link_id` TEXT NULL );

INSERT INTO `notifications` (`id`, `title`, `body`, `timestamp`, `read`, `type`, `link_id`) VALUES ('notif_1', '🔴 ¡Partido en Vivo Activo!', 'Gran Final: Galán / Lebrón vs Coello / Tapia se está disputando en Pista Central.', 'Hace 5 min', '0', 'MATCH', 'match_live_01') ON DUPLICATE KEY UPDATE id = VALUES(id), title = VALUES(title), body = VALUES(body), timestamp = VALUES(timestamp), read = VALUES(read), type = VALUES(type), link_id = VALUES(link_id);
INSERT INTO `notifications` (`id`, `title`, `body`, `timestamp`, `read`, `type`, `link_id`) VALUES ('notif_2', '🎾 Horario de tu próximo partido', 'Atención: Tu partido de Cuartos de Final se jugará hoy a las 18:30 h en Pista 2.', 'Hace 1 hora', '0', 'MATCH', 'match_upcoming_02') ON DUPLICATE KEY UPDATE id = VALUES(id), title = VALUES(title), body = VALUES(body), timestamp = VALUES(timestamp), read = VALUES(read), type = VALUES(type), link_id = VALUES(link_id);
INSERT INTO `notifications` (`id`, `title`, `body`, `timestamp`, `read`, `type`, `link_id`) VALUES ('notif_3', '🏆 Inscripciones Abiertas', 'Se ha abierto la inscripción para la Copa Abierta Barcelona 2026.', 'Ayer', '1', 'TOURNAMENT', 'tour_open_barcelona') ON DUPLICATE KEY UPDATE id = VALUES(id), title = VALUES(title), body = VALUES(body), timestamp = VALUES(timestamp), read = VALUES(read), type = VALUES(type), link_id = VALUES(link_id);

-- ------------------------------------------------------------
-- Table: pairs
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `pairs`;
CREATE TABLE IF NOT EXISTS `pairs` (`id` TEXT NULL  PRIMARY KEY, `name` TEXT NOT NULL , `player1_id` TEXT NOT NULL , `player2_id` TEXT NOT NULL , `player1_name` TEXT NOT NULL , `player2_name` TEXT NOT NULL , `player1_avatar` TEXT NULL , `player2_avatar` TEXT NULL , `created_at` TEXT NULL , `status` TEXT NOT NULL , `tournaments_disputed` INTEGER NULL , `titles_won` INTEGER NULL );

INSERT INTO `pairs` (`id`, `name`, `player1_id`, `player2_id`, `player1_name`, `player2_name`, `player1_avatar`, `player2_avatar`, `created_at`, `status`, `tournaments_disputed`, `titles_won`) VALUES ('pair_galan_lebron', 'Galán / Lebrón', 'usr_ale_galan', 'usr_juan_lebron', 'Alejandro Galán', 'Juan Lebrón', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80', '2025-01-15', 'ACTIVE', '12', '7') ON DUPLICATE KEY UPDATE id = VALUES(id), name = VALUES(name), player1_id = VALUES(player1_id), player2_id = VALUES(player2_id), player1_name = VALUES(player1_name), player2_name = VALUES(player2_name), player1_avatar = VALUES(player1_avatar), player2_avatar = VALUES(player2_avatar), created_at = VALUES(created_at), status = VALUES(status), tournaments_disputed = VALUES(tournaments_disputed), titles_won = VALUES(titles_won);
INSERT INTO `pairs` (`id`, `name`, `player1_id`, `player2_id`, `player1_name`, `player2_name`, `player1_avatar`, `player2_avatar`, `created_at`, `status`, `tournaments_disputed`, `titles_won`) VALUES ('pair_coello_tapia', 'Coello / Tapia', 'usr_arturo_coello', 'usr_agustin_tapia', 'Arturo Coello', 'Agustín Tapia', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80', '2025-02-01', 'ACTIVE', '10', '5') ON DUPLICATE KEY UPDATE id = VALUES(id), name = VALUES(name), player1_id = VALUES(player1_id), player2_id = VALUES(player2_id), player1_name = VALUES(player1_name), player2_name = VALUES(player2_name), player1_avatar = VALUES(player1_avatar), player2_avatar = VALUES(player2_avatar), created_at = VALUES(created_at), status = VALUES(status), tournaments_disputed = VALUES(tournaments_disputed), titles_won = VALUES(titles_won);
INSERT INTO `pairs` (`id`, `name`, `player1_id`, `player2_id`, `player1_name`, `player2_name`, `player1_avatar`, `player2_avatar`, `created_at`, `status`, `tournaments_disputed`, `titles_won`) VALUES ('pair_chingotto_navarro', 'Chingotto / Navarro', 'usr_chingotto', 'usr_paquito', 'Fede Chingotto', 'Paquito Navarro', 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150&auto=format&fit=crop&q=80', '2025-03-10', 'ACTIVE', '8', '2') ON DUPLICATE KEY UPDATE id = VALUES(id), name = VALUES(name), player1_id = VALUES(player1_id), player2_id = VALUES(player2_id), player1_name = VALUES(player1_name), player2_name = VALUES(player2_name), player1_avatar = VALUES(player1_avatar), player2_avatar = VALUES(player2_avatar), created_at = VALUES(created_at), status = VALUES(status), tournaments_disputed = VALUES(tournaments_disputed), titles_won = VALUES(titles_won);
INSERT INTO `pairs` (`id`, `name`, `player1_id`, `player2_id`, `player1_name`, `player2_name`, `player1_avatar`, `player2_avatar`, `created_at`, `status`, `tournaments_disputed`, `titles_won`) VALUES ('pair_stupaczuk_dinenno', 'Stupaczuk / Di Nenno', 'usr_stupa', 'usr_dinenno', 'Franco Stupaczuk', 'Martin Di Nenno', 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80', 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80', '2025-01-20', 'ACTIVE', '9', '3') ON DUPLICATE KEY UPDATE id = VALUES(id), name = VALUES(name), player1_id = VALUES(player1_id), player2_id = VALUES(player2_id), player1_name = VALUES(player1_name), player2_name = VALUES(player2_name), player1_avatar = VALUES(player1_avatar), player2_avatar = VALUES(player2_avatar), created_at = VALUES(created_at), status = VALUES(status), tournaments_disputed = VALUES(tournaments_disputed), titles_won = VALUES(titles_won);

-- ------------------------------------------------------------
-- Table: tournaments
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `tournaments`;
CREATE TABLE IF NOT EXISTS `tournaments` (`id` TEXT NULL  PRIMARY KEY, `name` TEXT NOT NULL , `logo` TEXT NULL , `description` TEXT NULL , `category` TEXT NULL , `level` TEXT NULL , `location` TEXT NULL , `start_date` TEXT NULL , `end_date` TEXT NULL , `status` TEXT NULL , `format` TEXT NULL , `max_pairs` INTEGER NULL , `registered_pair_ids` TEXT NULL , `rules` TEXT NULL , `court_ids` TEXT NULL );

INSERT INTO `tournaments` (`id`, `name`, `logo`, `description`, `category`, `level`, `location`, `start_date`, `end_date`, `status`, `format`, `max_pairs`, `registered_pair_ids`, `rules`, `court_ids`) VALUES ('tour_major_madrid', 'Premier Padel Major Madrid 2026', '🏆', 'El torneo oficial más prestigioso de la temporada con las mejores 16 parejas del circuito.', 'Masculino', 'Profesional', 'Wizink Center, Madrid', '2026-08-10', '2026-08-16', 'ACTIVE', 'Grupos + eliminación directa', '16', '["pair_galan_lebron", "pair_coello_tapia", "pair_chingotto_navarro", "pair_stupaczuk_dinenno"]', '{"sets_to_win": 2, "golden_point": true, "tie_break_at": 6, "final_set_tie_break": true, "points_distribution": {"champion": 1000, "runner_up": 600, "semi_finals": 360, "quarter_finals": 180, "group_stage": 90}}', '["crt_central", "crt_2"]') ON DUPLICATE KEY UPDATE id = VALUES(id), name = VALUES(name), logo = VALUES(logo), description = VALUES(description), category = VALUES(category), level = VALUES(level), location = VALUES(location), start_date = VALUES(start_date), end_date = VALUES(end_date), status = VALUES(status), format = VALUES(format), max_pairs = VALUES(max_pairs), registered_pair_ids = VALUES(registered_pair_ids), rules = VALUES(rules), court_ids = VALUES(court_ids);
INSERT INTO `tournaments` (`id`, `name`, `logo`, `description`, `category`, `level`, `location`, `start_date`, `end_date`, `status`, `format`, `max_pairs`, `registered_pair_ids`, `rules`, `court_ids`) VALUES ('tour_open_barcelona', 'Copa Abierta Barcelona 2026', '🎾', 'Competición de categoría Mixto Abierto con fases de grupos intensas y eliminatorias.', 'Mixto', 'Avanzado', 'Real Club de Tenis Barcelona', '2026-09-01', '2026-09-05', 'REGISTRATION', 'Fase de grupos', '12', '["pair_chingotto_navarro", "pair_stupaczuk_dinenno"]', '{"sets_to_win": 2, "golden_point": true, "tie_break_at": 6, "final_set_tie_break": true, "points_distribution": {"champion": 500, "runner_up": 300, "semi_finals": 180, "quarter_finals": 90, "group_stage": 45}}', '["crt_3", "crt_4"]') ON DUPLICATE KEY UPDATE id = VALUES(id), name = VALUES(name), logo = VALUES(logo), description = VALUES(description), category = VALUES(category), level = VALUES(level), location = VALUES(location), start_date = VALUES(start_date), end_date = VALUES(end_date), status = VALUES(status), format = VALUES(format), max_pairs = VALUES(max_pairs), registered_pair_ids = VALUES(registered_pair_ids), rules = VALUES(rules), court_ids = VALUES(court_ids);
INSERT INTO `tournaments` (`id`, `name`, `logo`, `description`, `category`, `level`, `location`, `start_date`, `end_date`, `status`, `format`, `max_pairs`, `registered_pair_ids`, `rules`, `court_ids`) VALUES ('tour_nocturno_sevilla', 'Torneo Nocturno Sevilla', '🌙', 'Edición nocturna exprés en formato Eliminación Directa.', 'Masculino', 'Principiante', 'Padel Club Sevilla', '2026-09-20', '2026-09-22', 'UPCOMING', 'Eliminación directa', '8', '["pair_coello_tapia"]', '{"sets_to_win": 2, "golden_point": false, "tie_break_at": 6, "final_set_tie_break": true, "points_distribution": {"champion": 250, "runner_up": 150, "semi_finals": 90, "quarter_finals": 45, "group_stage": 20}}', '["crt_2"]') ON DUPLICATE KEY UPDATE id = VALUES(id), name = VALUES(name), logo = VALUES(logo), description = VALUES(description), category = VALUES(category), level = VALUES(level), location = VALUES(location), start_date = VALUES(start_date), end_date = VALUES(end_date), status = VALUES(status), format = VALUES(format), max_pairs = VALUES(max_pairs), registered_pair_ids = VALUES(registered_pair_ids), rules = VALUES(rules), court_ids = VALUES(court_ids);

-- ------------------------------------------------------------
-- Table: users
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (`id` TEXT NULL  PRIMARY KEY, `name` TEXT NOT NULL , `surname` TEXT NOT NULL , `username` TEXT NOT NULL , `email` TEXT NOT NULL , `role` TEXT NOT NULL , `avatar` TEXT NULL , `level` TEXT NULL , `position` TEXT NULL , `dominant_hand` TEXT NULL , `current_pair_id` TEXT NULL , `points` INTEGER NULL DEFAULT 0, `partner_name` TEXT NULL , `phone` TEXT NULL , `stats` TEXT NULL );

INSERT INTO `users` (`id`, `name`, `surname`, `username`, `email`, `role`, `avatar`, `level`, `position`, `dominant_hand`, `current_pair_id`, `points`, `partner_name`, `phone`, `stats`) VALUES ('usr_carlos_admin', 'Carlos', 'Gómez', 'carlospadel', 'carlos@padelpro.app', 'ADMIN', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80', 'Avanzado', 'Revés (Izquierda)', NULL, NULL, '1520', NULL, '+34 612 345 678', '{"pointsWon": 1842, "winners": 312, "smashes": 180, "smashesWon": 142, "voleasWon": 128, "bandejas": 95, "viboras": 64, "remates": 110, "netPointsWon": 412, "touches": 4210, "shots": 3890, "serves": 820, "firstServes": 610, "secondServes": 210, "aces": 42, "doubleFaults": 18, "breakPoints": 94, "breakPointsWon": 58, "recoveries": 182, "globos": 340, "devoluciones": 680, "pointsSaved": 88, "unforcedErrors": 187, "distanceKm": 94.3, "timePlayedMin": 1420, "avgSpeedKmh": 12.4, "movesCount": 2840, "matchesPlayed": 24, "matchesWon": 17, "matchesLost": 7, "setsWon": 38, "setsLost": 21, "gamesWon": 241, "gamesLost": 198}') ON DUPLICATE KEY UPDATE id = VALUES(id), name = VALUES(name), surname = VALUES(surname), username = VALUES(username), email = VALUES(email), role = VALUES(role), avatar = VALUES(avatar), level = VALUES(level), position = VALUES(position), dominant_hand = VALUES(dominant_hand), current_pair_id = VALUES(current_pair_id), points = VALUES(points), partner_name = VALUES(partner_name), phone = VALUES(phone), stats = VALUES(stats);
INSERT INTO `users` (`id`, `name`, `surname`, `username`, `email`, `role`, `avatar`, `level`, `position`, `dominant_hand`, `current_pair_id`, `points`, `partner_name`, `phone`, `stats`) VALUES ('usr_1787371091916', 'luis', 'torres', 'lucho', 'lucho@gmail.com', 'PLAYER', 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80', 'Intermedio', 'Drive (Derecha)', NULL, NULL, '0', NULL, '25473547356354', '{"pointsWon": 0, "winners": 0, "smashes": 0, "smashesWon": 0, "voleasWon": 0, "bandejas": 0, "viboras": 0, "remates": 0, "netPointsWon": 0, "touches": 0, "shots": 0, "serves": 0, "firstServes": 0, "secondServes": 0, "aces": 0, "doubleFaults": 0, "breakPoints": 0, "breakPointsWon": 0, "recoveries": 0, "globos": 0, "devoluciones": 0, "pointsSaved": 0, "unforcedErrors": 0, "distanceKm": 0, "timePlayedMin": 0, "avgSpeedKmh": 0, "movesCount": 0, "matchesPlayed": 0, "matchesWon": 0, "matchesLost": 0, "setsWon": 0, "setsLost": 0, "gamesWon": 0, "gamesLost": 0}') ON DUPLICATE KEY UPDATE id = VALUES(id), name = VALUES(name), surname = VALUES(surname), username = VALUES(username), email = VALUES(email), role = VALUES(role), avatar = VALUES(avatar), level = VALUES(level), position = VALUES(position), dominant_hand = VALUES(dominant_hand), current_pair_id = VALUES(current_pair_id), points = VALUES(points), partner_name = VALUES(partner_name), phone = VALUES(phone), stats = VALUES(stats);

-- ------------------------------------------------------------
-- Table: users_auth
-- ------------------------------------------------------------
DROP TABLE IF EXISTS `users_auth`;
CREATE TABLE IF NOT EXISTS `users_auth` (`id` VARCHAR(255) PRIMARY KEY, `email` TEXT NOT NULL UNIQUE, `hashed_password` TEXT NOT NULL, `role` TEXT NOT NULL);

INSERT INTO `users_auth` (`id`, `email`, `hashed_password`, `role`) VALUES ('usr_carlos_admin', 'admin@padelpro.app', '$2b$12$8Z0bgAQi.WEuwZ5bJ4wqfuqElKuyofx4/WupEitolw9w2hodwxXQS', 'ADMIN') ON DUPLICATE KEY UPDATE id = VALUES(id), email = VALUES(email), hashed_password = VALUES(hashed_password), role = VALUES(role);

SET FOREIGN_KEY_CHECKS = 1;

-- ============================================================
-- Seed completed successfully
-- ============================================================